### ISSUE TITLE
Generated .nar archives cannot be uploaded a nar bundle to the NiFi Registry

### ISSUE THREAD

**Issue by EndzeitBegins** [lhotari/gradle-nar-plugin#2]
Newer version of the NiFi Registry support the upload of NAR bundles for centralized management.
However, .nar archives generated using the plugin cannot be uploaded and result in an `NullPointerException` / internal server error.

```
2022-11-17 23:01:55,630 ERROR [NiFi Registry Web Server-18] o.a.n.r.web.mapper.ThrowableMapper An unexpected error has occurred: org.apache.nifi.registry.bundle.extract.BundleException: Unable to create build info for bundle due to: null. Returning Internal Server Error response.
org.apache.nifi.registry.bundle.extract.BundleException: Unable to create build info for bundle due to: null
	at org.apache.nifi.registry.bundle.extract.nar.NarBundleExtractor.getBuildInfo(NarBundleExtractor.java:150)
	at org.apache.nifi.registry.bundle.extract.nar.NarBundleExtractor.extract(NarBundleExtractor.java:82)
	at org.apache.nifi.registry.service.extension.StandardExtensionService.createBundleVersion(StandardExtensionService.java:192)
	at org.apache.nifi.registry.web.service.StandardServiceFacade.createBundleVersion(StandardServiceFacade.java:526)
	at org.apache.nifi.registry.web.service.StandardServiceFacade$$FastClassBySpringCGLIB$$8b3bf0a8.invoke(<generated>)
        ...
Caused by: java.lang.NullPointerException: null
	at java.base/java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1470)
	at java.base/java.text.DateFormat.parse(DateFormat.java:393)
	at org.apache.nifi.registry.bundle.extract.nar.NarBundleExtractor.getBuildInfo(NarBundleExtractor.java:135)
        ...
```
 
This can be tracked down to some properties missing inside the `MANIFEST:MF` file.

After adding the properties `Build-Timestamp` and `Clone-During-Instance-Class-Loading` to the `MANIFEST:MF` using the task configuration, a different issue becomes apparent.
```kotlin
tasks {
    nar {
        manifest {
            attributes(
                "Build-Timestamp" to "${Instant.now().truncatedTo(ChronoUnit.SECONDS)}",
                "Clone-During-Instance-Class-Loading" to "false",
            )
        }
    }
}
```

```
2022-11-17 22:51:41,645 ERROR [NiFi Registry Web Server-19] o.a.n.r.web.mapper.ThrowableMapper An unexpected error has occurred: org.apache.nifi.registry.bundle.extract.BundleException: Unable to find descriptor at 'META-INF/docs/extension-manifest.xml'. This NAR may need to be rebuilt with the latest version of the NiFi NAR Maven Plugin.. Returning Internal Server Error response.
org.apache.nifi.registry.bundle.extract.BundleException: Unable to find descriptor at 'META-INF/docs/extension-manifest.xml'. This NAR may need to be rebuilt with the latest version of the NiFi NAR Maven Plugin.
	at org.apache.nifi.registry.bundle.extract.nar.NarBundleExtractor.parseExtensionDocs(NarBundleExtractor.java:188)
	at org.apache.nifi.registry.bundle.extract.nar.NarBundleExtractor.extract(NarBundleExtractor.java:89)
	at org.apache.nifi.registry.service.extension.StandardExtensionService.createBundleVersion(StandardExtensionService.java:192)
       ...
```

This .xml file seems to be existing in the Maven plugin for a long time, but is not created when using the Gradle plugin.
Sadly, it seems to be required in order to be uploaded to the NiFi Registry.

**Comment by EndzeitBegins** [comment]
I've found a (quite ugly) workaround.

```kotlin
tasks {
    nar {
        // manual workaround to fix issue https://github.com/lhotari/gradle-nar-plugin/issues/2

        // 1. write extension-manifest.xml
        val extensionManifestFile = file("extension-manifest.xml")
        doFirst {
            val extensionManifestContent = """
                <extensionManifest>
                    <groupId>$group</groupId>
                    <artifactId>$artifactName</artifactId>
                    <version>${project.version}</version>
                    <systemApiVersion>${niFiVersion}</systemApiVersion>
                    <extensions/>
                </extensionManifest>
            """.trimIndent()

            extensionManifestFile.writeText(extensionManifestContent)
        }
        from(extensionManifestFile) {
            into("META-INF/docs/")
        }
        doLast {
            extensionManifestFile.delete()
        }

        // 2. add required attributes to MANIFEST.MF
        manifest {
            attributes(
                "Build-Timestamp" to "${Instant.now().truncatedTo(ChronoUnit.SECONDS)}",
                "Clone-During-Instance-Class-Loading" to "false",
            )
        }
    }
}
```

However, this requires adjustments in every project. I would love to see this fixed in the upstream repository / plugin instead.
Are you still maintaining this project @lhotari and / or would you accept pull-requests?

**Comment by lhotari** [comment]
> Are you still maintaining this project @lhotari and / or would you accept pull-requests?

@EndzeitBegins Yes, pull requests are welcome and accepted. I'm sorry for the delay in my response.
